// Banco de dados das tarefas dos alunos
const alunos = [
    {
        nome: "Carlos",
        tarefas: [
            { titulo: "Projeto Site de noticas usando JSON", descricao: "", status: "pendente", pontos: 3 },
            { titulo: "Video: Curriculo", descricao: "https://www.youtube.com/watch?v=q652jp6YVqk&pp=ygUNY3VycmljdWxvIGRldg%3D%3D", status: "pendente", pontos: 1 },
            { titulo: "Dailly 18/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 04/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Video JSON", descricao: "", status: "finalizado", pontos: 1 },
            {titulo: "Video XML", descricao: "https://www.youtube.com/watch?v=qSfoczpQifc", status: "finalizado", pontos: 3 },
            { titulo: "Vídeo API Tempo", descricao: "https://www.youtube.com/watch?v=qxzqEuAOYZ4&t=56s", status: "finalizado", pontos: 5 },
            { titulo: "Dailly 04/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 21/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 07/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 21/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Prova 1", descricao: "", status: "finalizado", pontos: 5 },
            { titulo: "Portfólio FeedBack", descricao: "", status: "finalizado", pontos: 2 },
            { titulo: "Portfólio CSS", descricao: "", status: "finalizado", pontos: 10 },
            { titulo: "FeedBack 23/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 23/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 09/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Site portfólio no GitHub", descricao: "", status: "finalizado", pontos: 2 },
            { titulo: "Video: Portifolio", descricao: "https://www.youtube.com/watch?v=Vr3hWm7My24", status: "finalizado", pontos: 2 },
            { titulo: "Dailly 09/09/25", descricao: "", status: "finalizado", pontos: 1 },
        ]
    },
    {
        nome: "Felipe",
        tarefas: [
            { titulo: "Projeto Site de noticas usando JSON", descricao: "", status: "pendente", pontos: 3 },
            { titulo: "Feedback sobre o portfólio", descricao: "", status: "pendente", pontos: 1 },
            { titulo: "Video JSON", descricao: "", status: "pendente", pontos: 1 },
            { titulo: "Portfólio CSS", descricao: "", status: "pendente", pontos: 10 },
            { titulo: "Site portfólio no GitHub", descricao: "", status: "finalizado", pontos: 2 },
            { titulo: "Dailly 18/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 11/11/25", descricao: "Código muito avançado leitura do JSON banco de dados", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 04/11/25", descricao: "Ter menos coisas para se fazer para finalizar a tempo", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 28/10/25", descricao: "planejar a aula com mapas mentais da estrutura do projeto", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 11/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 04/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 28/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 28/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 21/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 14/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 14/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 23/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 09/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 09/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 02/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 02/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Video: Portifolio", descricao: "https://www.youtube.com/watch?v=Vr3hWm7My24", status: "finalizado", pontos: 2 },
            { titulo: "FeedBack 26/08/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Fazer Curriculo", descricao: "Canvas.com", status: "finalizado", pontos: 2 },
            { titulo: "Dailly 26/08/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Video: Curriculo", descricao: "https://www.youtube.com/watch?v=q652jp6YVqk&pp=ygUNY3VycmljdWxvIGRldg%3D%3D", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 19/08/25", descricao: "", status: "finalizado", pontos: 1 },
        ]
    },
    {
        nome: "Eduardo",
        tarefas: [
            { titulo: "Video XML", descricao: "https://www.youtube.com/watch?v=qSfoczpQifc", status: "pendente", pontos: 3 },
            { titulo: "Video JSON", descricao: "https://www.youtube.com/watch?v=BWPUSXzSWA8", status: "pendente", pontos: 1 },
            { titulo: "Projeto Site de noticas usando JSON", descricao: "", status: "pendente", pontos: 3 },
            { titulo: "Site portfólio no GitHub", descricao: "", status: "pendente", pontos: 2 },
            { titulo: "FeedBack 04/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 28/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 21/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 21/10/25", descricao: "Respostas Genericas", status: "finalizado", pontos: 1 },
            { titulo: "Feedback sobre o portfólio", descricao: "", status: "finalizado", pontos: 0 },
            { titulo: "Video: Curriculo", descricao: "https://www.youtube.com/watch?v=q652jp6YVqk&pp=ygUNY3VycmljdWxvIGRldg%3D%3D", status: "pendente", pontos: 1 },
            { titulo: "FeedBack 30/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 23/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 09/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 09/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Feedback sobre o portfólio", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 02/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 02/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 19/08/25", descricao: "", status: "finalizado", pontos: 1 },
        ]
    }
    ,
    {
        nome: "Vitor",
        tarefas: [
            { titulo: "Dailly 18/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Video XML", descricao: "https://www.youtube.com/watch?v=qSfoczpQifc", status: "pendente", pontos: 3 },
            { titulo: "Video JSON", descricao: "https://www.youtube.com/watch?v=BWPUSXzSWA8", status: "pendente", pontos: 1 },
            { titulo: "Projeto Site de noticas usando JSON", descricao: "", status: "finalizado", pontos: 3 },
            { titulo: "Feedback sobre o portfólio", descricao: "", status: "pendente", pontos: 1 },
            { titulo: "Dailly 11/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Portfólio CSS", descricao: "", status: "finalizado", pontos: 10 },
            { titulo: "Dailly 28/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 09/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Feedback sobre o portfólio", descricao: "", status: "pendente", pontos: 1 },
            { titulo: "Dailly 21/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 21/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 21/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 07/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 30/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 07/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 21/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Prova 1", descricao: "", status: "finalizado", pontos: 5 },
            { titulo: "FeedBack 23/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 30/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 23/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 02/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Site portfólio no GitHub", descricao: "", status: "finalizado", pontos: 2 },            
            { titulo: "Dailly 02/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Video: Portifolio", descricao: "https://www.youtube.com/watch?v=Vr3hWm7My24", status: "finalizado", pontos: 2 },
            { titulo: "FeedBack 26/08/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Fazer Curriculo", descricao: "Canvas.com", status: "finalizado", pontos: 2 },
            { titulo: "Dailly 26/08/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Video: Curriculo", descricao: "https://www.youtube.com/watch?v=q652jp6YVqk&pp=ygUNY3VycmljdWxvIGRldg%3D%3D", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 19/08/25", descricao: "", status: "finalizado", pontos: 1 },
        ]
    },
    {
        nome: "Arthur",
        tarefas: [
            { titulo: "Vídeo API Tempo", descricao: "https://www.youtube.com/watch?v=qxzqEuAOYZ4&t=56s", status: "pendente", pontos: 5 },
            { titulo: "Projeto Site de noticas usando JSON", descricao: "", status: "pendente", pontos: 3 },
            { titulo: "FeedBack 04/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Video XML", descricao: "https://www.youtube.com/watch?v=qSfoczpQifc", status: "finalizado", pontos: 3 },
            { titulo: "Dailly 04/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 28/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 21/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 21/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 14/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Video JSON", descricao: "https://www.youtube.com/watch?v=BWPUSXzSWA8", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 14/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Prova 1", descricao: "", status: "finalizado", pontos: 5 },
            { titulo: "Feedback sobre o portfólio", descricao: "", status: "finalizado", pontos: 2 },
            { titulo: "Dailly 30/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Video JSON", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 30/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 23/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 23/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Portfólio CSS", descricao: "", status: "finalizado", pontos: 10 },
            { titulo: "FeedBack 23/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 09/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 09/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 02/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Site portfólio no GitHub", descricao: "", status: "finalizado", pontos: 2 },
            { titulo: "Dailly 02/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Video: Portifolio", descricao: "https://www.youtube.com/watch?v=Vr3hWm7My24", status: "finalizado", pontos: 2 },
            { titulo: "Fazer Curriculo", descricao: "Canvas.com", status: "finalizado", pontos: 2 },
            { titulo: "Dailly 26/08/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Video: Curriculo", descricao: "https://www.youtube.com/watch?v=q652jp6YVqk&pp=ygUNY3VycmljdWxvIGRldg%3D%3D", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 19/08/25", descricao: "", status: "finalizado", pontos: 1 },
        ]
    }
    ,
    {
        nome: "Luis",
        tarefas: [
            { titulo: "Projeto Hamburgueria GitHub e Portfolio", descricao: "", status: "pendente", pontos: 3 },
            { titulo: "Projeto Hamburgueria FeedBack", descricao: "", status: "pendente", pontos: 3 },
            { titulo: "Projeto Hamburgueria CSS", descricao: "", status: "pendente", pontos: 3 },
            { titulo: "Projeto Hamburgueria JS", descricao: "", status: "pendente", pontos: 3 },
            { titulo: "Projeto Hamburgueria HTML", descricao: "", status: "pendente", pontos: 3 },
            { titulo: "Dailly 18/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 11/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 04/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 28/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Video XML", descricao: "https://www.youtube.com/watch?v=qSfoczpQifc", status: "finalizado", pontos: 3 },
            { titulo: "Video JSON", descricao: "https://www.youtube.com/watch?v=BWPUSXzSWA8", status: "finalizado", pontos: 1 },
            { titulo: "Projeto Site de noticas usando JSON", descricao: "", status: "finalizado", pontos: 3 },
            { titulo: "Video JSON", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 11/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 04/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 28/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 21/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 21/10/25", descricao: "Respostas Genericas", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 14/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 07/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Feedback sobre o portfólio", descricao: "", status: "finalizado", pontos: 2 },
            { titulo: "FeedBack 30/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack portfólio CSS", descricao: "Sem nome de avaliador", status: "finalizado", pontos: 0 },
            { titulo: "Dailly 21/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 14/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Prova 1", descricao: "", status: "finalizado", pontos: 5 },
            { titulo: "Dailly 30/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Site portfólio CSS", descricao: "", status: "finalizado", pontos: 10 },
            { titulo: "Dailly 23/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 23/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 09/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 09/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 02/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Site portfólio no GitHub", descricao: "", status: "finalizado", pontos: 2 },
            { titulo: "Dailly 02/09/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Video: Portifolio", descricao: "https://www.youtube.com/watch?v=Vr3hWm7My24", status: "finalizado", pontos: 2 },
            { titulo: "FeedBack 26/08/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Fazer Curriculo", descricao: "Canvas.com", status: "finalizado", pontos: 2 },
            { titulo: "Dailly 26/08/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Video: Curriculo", descricao: "https://www.youtube.com/watch?v=q652jp6YVqk&pp=ygUNY3VycmljdWxvIGRldg%3D%3D", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 19/08/25", descricao: "", status: "finalizado", pontos: 1 },
        ]
    },

    {
        nome: "Natan",
        tarefas: [
            { titulo: "Video Lista de Tarefas", descricao: "", status: "pendente", pontos: 2 },
            { titulo: "Dailly 18/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 11/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 04/11/25", descricao: "Fazer commits e criar repositórios no GitHub", status: "finalizado", pontos: 1 },
            { titulo: "Projeto Site de noticas usando JSON", descricao: "", status: "finalizado", pontos: 3 },
            { titulo: "Vídeo HTML & CSS", descricao: "https://youtu.be/n_Etdr7Dbjs?si=cMatCETdG0apb_sR", status: "finalizado", pontos: 2 },
            { titulo: "Dailly 11/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 04/11/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 28/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 21/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 14/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "FeedBack 07/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 21/10/25", descricao: "", status: "finalizado", pontos: 1 },
            { titulo: "Dailly 14/10/25", descricao: "", status: "finalizado", pontos: 1 },
        ]
    }
];
